apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        region: home
      containers:
        - name: gateway
          image: #{IMAGE}
          ports:
            - containerPort: 8888
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/etc
      volumes:
        - name: config
          configMap:
            name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powernotes-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - powernotes-api.flightdeck.tech
      secretName: powernotes-api-flightdeck-tech-tls
  rules:
    - host: powernotes-api.flightdeck.tech
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway
                port:
                  number: 80