// Code generated by goctl. DO NOT EDIT.
package types

type Flow struct {
	ID          int64  `json:"id,optional"`
	ProjectName string `json:"project_name"`
	Name        string `json:"name"`
	CreatedAt   int64  `json:"created_at,optional"`
	UpdatedAt   int64  `json:"updated_at,optional"`
}

type FlowNoteRelation struct {
	FlowID   int64 `json:"flow_id"`
	NoteID   int64 `json:"note_id"`
	Position int   `json:"position"`
}

type Note struct {
	ID            int64  `json:"id,optional"`
	ProjectName   string `json:"project_name"`
	FileName      string `json:"file_name"`
	FilePath      string `json:"file_path"`
	LineNumber    int    `json:"line_number"`
	EndLineNumber int    `json:"end_line_number,optional"`
	Text          string `json:"text"`
	CreatedAt     int64  `json:"created_at,optional"`
	UpdatedAt     int64  `json:"updated_at,optional"`
}

type IDRequest struct {
	ID int64 `path:"id"`
}

type FlowNoteIDRequest struct {
	FlowID int64 `path:"flow_id"`
	NoteID int64 `path:"note_id"`
}

type SwapFlowNoteRequest struct {
	FlowID   int64 `json:"flow_id"`
	NoteID   int64 `json:"note_id"`
	Position int   `json:"position"`
	Offset   int   `json:"offset"`
}
